mysql <<EOFMYSQL
use nawojtow;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS SECTION;
DROP TABLE IF EXISTS PROFESSOR;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS ROOM;
DROP TABLE IF EXISTS DEPT;
DROP TABLE IF EXISTS Bookstore;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Copy;
DROP TABLE IF EXISTS Purchase;

SET FOREIGN_KEY_CHECKS = 1;

EOFMYSQL